### ISSUE TITLE
Terraform destroy on windows machines

### ISSUE THREAD

**Issue by TristanBoland** [combinator-ml/terraform-k8s-istio#3]
# Summary

When using the the combinator module we ran into an issue regarding destroying the infrastructure.
Running terraform destroy on mac machines runs fine, on windows machines however the rm -rf command simply doesn't exist. 
This causes issues when running locally on windows development machines!

# Exception

![image](https://user-images.githubusercontent.com/49944460/137500749-d56eda89-7cfc-42ea-82cd-6ef0868a639a.png)

**Comment by philwinder** [comment]
Oh noes Windows!

I think the simplest option is to simply remove the [on_destroy command](https://github.com/combinator-ml/terraform-k8s-istio/blob/main/istio.tf#L8) from your script.

None of us use windows. @TristanBoland Can you try deleting those lines and run them again?

Obviously it won't delete the downloaded file at that point but I don't think that's a big problem.

Thanks!

**Comment by TristanBoland** [comment]
Our team uses both windows and mac machines, so far we have removed the on destroy command as a quick fix.
We will most likely add a fix in the near future, we could fork the project and create a PR to this repo if we do end up adding a fix. 

Thank you for the response!

**Comment by philwinder** [comment]
Thanks Tristan. I don't mind removing it either, since it's just part of the cleanup.
